services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: dockerized
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dockerized
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: ${TARGET_STAGE:-dev}
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: ${TARGET_STAGE:-dev}
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend-dist:/app/dist
      - /app/node_modules

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
      target: ${TARGET_STAGE:-dev}
    ports:
      - "80:80"
    depends_on:
      - frontend
    volumes:
      - frontend-dist:/usr/share/nginx/html

volumes:
  pgdata:
  frontend-dist:
