services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: dockerized
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dockerized
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: ${TARGET_STAGE:-dev}
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: ${TARGET_STAGE:-dev}
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  pgdata:
